components_manager:
    coro_pool:
        initial_size: 100
        max_size: 1000
    
    event_thread_pool:
        threads: 2
    
    task_processors:
        main-task-processor:
            thread_name: main-worker
            worker_threads: 16
            spinning-iterations: 500
            task-processor-queue: work-stealing-task-queue
        
        monitor-task-processor:
            thread_name: monitor-worker
            worker_threads: 2
            os-scheduling: low-priority
            task-processor-queue: global-task-queue
        
        fs-task-processor:
            thread_name: fs-worker
            worker_threads: 2
            os-scheduling: low-priority
            task-processor-queue: global-task-queue
        
        bg-task-processor:
            thread_name: bg-worker
            worker_threads: 2
            os-scheduling: idle
            task-processor-queue: global-task-queue
        
    default_task_processor: main-task-processor

    components:
        manager-controller:

        server:
            listener:
                address: 127.0.0.1
                port: 10000
                task_processor: main-task-processor
            
            listener-monitor:
                address: 127.0.0.1
                port: 10001
                task_processor: monitor-task-processor
        
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    format: tskv
                    overflow_behavior: discard

        fs-cache-main:
            dir: '/workspaces/auth-service/auth-service/static'
            fs-task-processor: fs-task-processor
            update-period: 10s

        handler-static:
            fs-cache-component: fs-cache-main
            path: /*
            method: GET
        
        http-client:
            pool-statistics-disable: true
            thread-name-prefix: http-client
            threads: 2
            fs-task-processor: fs-task-processor
            user-agent: auth-service
            testsuite-enabled: true
            testsuite-timeout: 5s
            testsuite-allowed-url-prefixes: ['http://localhost:8083/']
        
        dns-client:
            fs-task-processor: fs-task-processor
            hosts-file-path: /etc/hosts
            hosts-file-update-interval: 10m
        
        testsuite-support:
            testsuite-pg-execute-timeout: 300ms
            testsuite-pg-statement-timeout: 300ms
            cache-update-execution: concurrent
        
        handler-ping:
            path: /ping
            task_processor: main-task-processor
            method: GET,HEAD
            max_request_size: 256
            max_headers_size: 256
            url_trailing_slash: strict-match
            request_body_size_log_limit: 128
            response_data_size_log_limit: 128
            decompress_request: false
            throttling_enabled: false
            set-response-server-hostname: false
            log-level: WARNING
        
        handler-resources:
            path: /static/{subpath}
            task_processor: main-task-processor
            method: GET
        
        handler-register-user:
            path: /api/v1/register
            task_processor: main-task-processor
            method: POST
            url_trailing_slash: strict-match
            request_body_size_log_limit: 128
            response_data_size_log_limit: 128
            decompress_request: false
            log-level: WARNING

        handler-login-user:
            path: /api/v1/login
            task_processor: main-task-processor
            method: GET
            url_trailing_slash: strict-match
            request_body_size_log_limit: 128
            response_data_size_log_limit: 128
            decompress_request: false
            log-level: WARNING
        
        handler-remove-user:
            path: /users/{uid}
            task_processor: main-task-processor
            method: DELETE
            url_trailing_slash: strict-match
            request_body_size_log_limit: 128
            response_data_size_log_limit: 128
            decompress_request: false
            log-level: WARNING
        
        auth-db:
            dbconnection: 'postgresql://auth-backend:cct5VZto1GJkIiuBDU57v5cRKTioDFctz2oLoRA3CAUeLk2EY3@localhost:5432/auth_service_db'
            blocking_task_processor: fs-task-processor